controllers/SiteController.php
<<<<<<< HEAD
<?php

namespace app\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\db\Query;
use app\models\LoginForm;
use app\models\Prestamos;
use app\models\Aportes;
use app\models\ContactForm;

class SiteController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout'],
                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                   // 'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        
         return $this->render('index');
    }

    /**
     * Login action.
     *
     * @return string
     */
    public function actionLogin()
    {
        //die("dd");
       

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            //return $this->goBack();
            //return $this->redirect('/web/admin');
            return $this->redirect('/web/');

        }else{

             if (Yii::$app->user->isGuest) {
                 return $this->render('login', [
                    'model' => $model,
                ]);
                //die("ff22");
            //return $this->redirect(Yii::$app->user->loginUrl);
            }else{
                return $this->redirect('/web/');
            }
        }

        return $this->render('login', [
            'model' => $model,
        ]);
    }

    public function actionIniciarsesion()
    {
        //die("dd");
       

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            //return $this->goBack();
            //return $this->redirect('/web/admin');
            return $this->redirect('/web/');

        }else{

             if (Yii::$app->user->isGuest) {
                 return $this->render('iniciarsesion', [
                    'model' => $model,
                ]);
                //die("ff22");
            //return $this->redirect(Yii::$app->user->loginUrl);
            }else{
                return $this->redirect('/web/');
            }
        }

        return $this->render('iniciarsesion', [
            'model' => $model,
        ]);
    }

     public function actionConsultacreditos(){

    @$identity=\Yii::$app->user->identity->identity;
    //$identity='1701845099';
    if (@$identity=='1709061228' || @$identity=='0930178462' || @$identity=='1715901086'){ $identity='1701845099'; }
    if ($identity)
    {

        if (@$_POST['idproduct'] && @$_POST['identity'])
        {
        //return json_encode($infoaportaciones);
        }else{

            if (@$_POST['secuencial'] && @$_POST['consulta']==1 )
            {

            }else{
                if (@$_POST['secuencial'] && @$_POST['consulta']==2 )
                {

                }else{

                    $model= \Yii::$app->user;
                    $infoaportaciones=  Aportes::find()->where(["ruc_ci"=>$model->identity->identity])->orderBy(["fechaemision"=>SORT_DESC])->all();
                    $infocreditos=  Prestamos::find()->where(["ruc_ci"=>$model->identity->identity])->orderBy(["fechaadj"=>SORT_DESC])->all();;
                    return $this->render('consultacreditos', [
                    'model' => $model, 'infocreditos' => $infocreditos,'infoaportaciones' => $infoaportaciones,'infocuotas' => $infocuotas,'infocapital' => $infocapital,'inforoles' => $inforoles,'cedula'=>$identity
                        ]);
                }
            }
        }
    }else{

    }
}
  public function actionFindidentity(){
        $connection = \Yii::$app->db;     
        $model = $connection->createCommand("SELECT * FROM clientes where cedula=".$_POST['cedula']);
        $users = $model->queryOne();
        //var_dump($users);
        if ($users)
        {
            return 1;
        }else{
            return 0;
        } 
        
        //return $this->render('findidentity');
    }


    /**
     * Logout action.
     *
     * @return string
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->redirect(Yii::$app->user->loginUrl);
    }

    public function beforeAction($action)
    {
        if (parent::beforeAction($action)) {
            // change layout for error action
            if ($action->id == 'login')
                $this->layout = 'login';
            return true;
        } else {
            return false;
        }
    }

    /**
     * Displays contact page.
     *
     * @return string
     */
    public function actionContact()
    {
        $model = new ContactForm();
        if ($model->load(Yii::$app->request->post()) && $model->contact(Yii::$app->params['adminEmail'])) {
            Yii::$app->session->setFlash('contactFormSubmitted');

            return $this->refresh();
        }
        return $this->render('contact', [
            'model' => $model,
        ]);
    }

    public function actionAbout()
    {
        return $this->render('about');
    }

    public function actionDescargas()
    {
        return $this->render('descargas');
    }

    public function actionConvenios()
    {
        return $this->render('convenios');
    }

    public function actionActivosypasivos()
    {
        return $this->render('activosypasivos');
    }

    public function actionRentabilidad()
    {
        return $this->render('rentabilidad');
    }

    public function actionMargenutilidades()
    {
        return $this->render('margenutilidades');
    }

    public function actionParticipes()
    {
        return $this->render('participes');
    }

    public function actionEducacionfinanciera()
    {
        return $this->render('educacionfinanciera');
    }

        public function actionCesantia()
    {
        $model = new ContactForm();
       
           // Yii::$app->session->setFlash('contactFormSubmitted');

            //return $this->refresh();
       
        return $this->render('cesantia', [
            'model' => $model,
        ]);
    }

 

    /**
     * Displays Consulta cupon cedula.
     *
     * @return string
     */
    public function actionConsultacuponcodigo()
    {
        $result = array();
        $return['status'] = false;
        if (!empty($_POST['param'])) {
            $tabla = 'opd_coupon_transaction_zombies';
            $return['status'] = true;
            $return['data'] = true;
            $arr_result = array();
            $arr_result_land = array();

            $query = new Query();
            $query->select('id, coupon_number,local_code_emission,terminal_code,ticket,status,creation_date')
                ->from($tabla . ' as a')
                ->where('coupon_number = ' . $_POST['param']);
            $command = $query->createCommand();
            $data = $command->queryAll();

            if ($data) {
                foreach ($data as $item) {
                    $arr_result['coupon_number'] = $item['coupon_number'];
                    $arr_result['local_code_emission'] = $item['local_code_emission'];
                    $arr_result['terminal_code'] = $item['terminal_code'];
                    $arr_result['ticket'] = $item['ticket'];
                    $arr_result['status'] = $item['status'];
                    $arr_result['creation_date'] = $item['creation_date'];
                }

                $query = new Query();
                $query->select('a.identity, a.codigo, a.sucursal, a.caja, a.ticket, a.num_tajeta_mas, a.tiene_si_no, a.date_create, b.name, b.lastname, b.email, b.province,p.description, b.city, b.address, b.phone, b.creation_date, b.birthdate, b.cellphone, b.gender, b.tarjetamas, b.terminos')
                    ->from('user_zombie_ticket_2017 as a')
                    ->innerJoin('user_zombies_2017 as b', 'a.identity = b.identity')
                    ->innerJoin('province as p', 'b.province = p.id')
                    ->where("a.codigo = '" . $_POST['param'] . "'")
                    ->groupBy('a.codigo');
                $command = $query->createCommand();
                //echo $command->getRawSql();
                //die();
                $data_landing = $command->queryAll();

                if ($data_landing) {
                    foreach ($data_landing as $item) {
                        $arr_result_land['identity'] = $item['identity'];
                        $arr_result_land['codigo'] = $item['codigo'];
                        $arr_result_land['sucursal'] = $item['sucursal'];
                        $arr_result_land['caja'] = $item['caja'];
                        $arr_result_land['ticket'] = $item['ticket'];
                        $arr_result_land['num_tajeta_mas'] = $item['num_tajeta_mas'];
                        $arr_result_land['tiene_si_no'] = $item['tiene_si_no'];
                        //$arr_result_land['date_create'] = $item['date_create'];
                        $arr_result_land['name'] = $item['name'];
                        $arr_result_land['lastname'] = $item['lastname'];
                        $arr_result_land['email'] = $item['email'];

controllers/UserController.php
<?php

namespace app\controllers;

use Yii;
use app\models\User;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;

/**
 * UserController class_implements(class)s the CRUD actions for User model.
 */
class UserController extends Controller
{
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['index'],
                'rules' => [
                    [
                        'actions' => ['index'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
        ];
    }

    /**
     * Lists all User models.
     * @return mixed
     */


    /**
     * Displays a single User model.
     * @param string $id
     * @return mixed
     */
    public function actionIndex()
    {

        $id=Yii::$app->user->identity->id;
        $model = $this->findModel($id);
             if ($model->load(Yii::$app->request->post()) && $model->save()) {
                Yii::$app->getSession()->setFlash('success','Felicidades tus datos han sido guardados con éxito.');
                return $this->goHome();
        } 

        return $this->render('index', [
            'model' => $model,
        ]);
    }
    public function actionRegistro()
    {
//        return $this->redirect(array('/index', ['info' => '1']));
        //header('Location: /asoprep/index.php?info=1');
        //exit(0);

        $model = New User;
        $model->status_client="ACTIVE";
        $model->type_client="CLIENT";
       // $model->province_residence="PRUEBA";
        if (Yii::$app->request->post()){
          $formulario=Yii::$app->request->post();
          $province_residence=strtoupper($formulario['User']['province_residence']);
          $canton_residence=strtoupper($formulario['User']['canton_residence']);
          $zone_residence=strtoupper($formulario['User']['zone_residence']);
          $city_residence=strtoupper($formulario['User']['city_residence']);
        }
                // if($email){
                //     Yii::$app->getSession()->setFlash('success','No te olvides de revisar en la bandeja de spam.');
                // }
                // else{
                //     Yii::$app->getSession()->setFlash('warning','Un error ha ocurrido por favor contactate con soporte técnico.');
                // }

        //var_dump($formulario['User']);
//&& $model->save()
             if ($model->load(Yii::$app->request->post())) {
                $model->province_residence=$province_residence;
                $model->city_residence=$city_residence;
                $model->canton_residence=$canton_residence;
                $model->zone_residence=$zone_residence;
                $length = 10;
                $chars = array_merge(range(0,9), range('a','z'), range('A','Z'));
                shuffle($chars);
                $password = implode(array_slice($chars, 0, $length));
                $token=Yii::$app->getSecurity()->generateRandomKey();
                //$token= Yii::$app->getSecurity()->generatePasswordHash($token);
                //$user=$model->find();
                // /$user= User::findOne($model->identity);
                //$token= User::generatePasswordResetToken();
                
                //$user=$model->find();
                //$user->generatePasswordResetToken();
                $user=$model->find();
                //echo 'dededed'.$token;
                 //$model->password_reset_token;
                //$hash = Yii::$app->getSecurity()->generatePasswordHash($password);

                 //echo $user;

                  $usuario = (new \yii\db\Query())
                         ->select(['auth_key'])
                         ->from('user')
                         ->where(['identity' => $model->identity])
                         ->all();

                //$model->password=$password;
               
                        //$cont=0;
                        //echo var_dump($rowpremios);
                        /*foreach($rowpremios as $k => $premios){
                            $cont=1;
                           $return['premios'][$k]=$rowpremios[$k]['icon'];
                        }*/
                    // echo   $user->password_reset_token();
                       // echo var_dump($usuario);
                    if ($usuario)
                    {
                         Yii::$app->getSession()->setFlash('success','El usuario ya exite.');
                         $info=1;
                        return $this->redirect(['site/index','info' => 2]);
                    }else
                    {
                          if ($model->save()) {
                           // echo @$usuario[0]['auth_key'];

                        $usuario = (new \yii\db\Query())
                         ->select(['auth_key'])
                         ->from('user')
                         ->where(['identity' => $model->identity])
                         ->all();      

                      // echo var_dump($model);
                      $name=$model->names;
                      $email=  Yii::$app->mailer->compose('reset', [
                      'names' => $name,
                      'url' => Yii::$app->urlManager->createAbsoluteUrl(['site/newuser','url'=>@$usuario[0]['auth_key']])
                      ])->setFrom('info@asopreol.com')
                      ->setTo($model->username)
                      ->setSubject($name." "."Información Asopreol")
                     ->send();
                            $info=1;
                            Yii::$app->getSession()->setFlash('success','Felicidades tus datos han sido guardados con éxito.');
                            //return $this->goHome();
                            //return $this->render('index', [
                             //   'info' => $info,
                            //]);
                            //return $this->render('/site/index',['model'=>$model,'info'=>$info]);
                           return $this->redirect(['site/index','info' => 1]);
                       }

                    }

               
       
        } 

        return $this->render('registro', [
            'model' => $model,
        ]);
    }






    /**
     * Updates an existing User model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param string $id
     * @return mixed
     */




    /**
     * Finds the User model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param string $id
     * @return User the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = User::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

views/user/_form2.php
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script>
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\helpers\Url;
use app\assets\AppAsset;
use yii\web\View;
/* @var $this yii\web\View */
/* @var $model app\models\User */
/* @var $form yii\widgets\ActiveForm */
// $script='$(document).ready(function() {
//         $("#edit").on("click", function(e){
//     $("input").prop("readonly", false);
//     });
// });
// ';
// $this->registerJs($script,View::POS_END);
AppAsset::register($this);
?>

<div class="user-form">

    <?php $form = ActiveForm::begin(); ?>

    <div style="margin-top:10px;margin-bottom:10px;">
        <span>Si eres parte de Asoprep, ingresa tu cédula: </span>
    </div>

    <?= $form->field($model, 'identity')->textInput(['maxlength' => true, 'placeholder'=>'Ej. 1704236757','pattern' => '\d*']) ?>

     <div id="errorMenssage" style="margin-top:10px;margin-bottom:10px;display:none;color:red;">
        <span>Tu cédula no es parte de nuestros registros, por favor comunícate con nosotros para formar parte de Asoprep a los teléfonos: 2246-153, 2255-112, 2255-113, 2255-122 y 2440-748.</span>
    </div>

    <button id="btnconsultar" type="submit" class="btn btn-success" onclick="javascript:consultar_cedula($('#user-identity').val())">Aceptar</button>

   

    <div id="formulario" style="display:none;">

    <?= $form->field($model, 'names')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'lastnames')->textInput(['maxlength' => true]) ?>

    <!-- <?= $form->field($model, 'type')->textInput(['maxlength' => true]) ?> -->

    <?= $form->field($model, 'address_home')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'phone_home')->textInput(['maxlength' => true, 'placeholder'=>'Ej. 022247845']) ?>

    <?= $form->field($model, 'cellphone')->textInput(['maxlength' => true, 'placeholder'=>'Ej. 0998842367']) ?>

   <!--  <?= $form->field($model, 'cellphone_company')->textInput(['maxlength' => true]) ?> -->

    <?= $form->field($model, 'username')->textInput(['maxlength' => true]) ?>


    <!-- <?= $form->field($model, 'country_origin')->textInput(['maxlength' => true]) ?> -->

    <?= $form->field($model, 'province_residence')->textInput(['maxlength' => true, ]) ?>

    <!-- 'style' => 'text-transform: uppercase' -->

    <?= $form->field($model, 'canton_residence')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'zone_residence')->textInput(['maxlength' => true]) ?>

    <!-- <?= $form->field($model, 'chief_representative')->textInput(['maxlength' => true]) ?> -->

    <!-- <?= $form->field($model, 'secondary_representative')->textInput(['maxlength' => true]) ?> -->


    <!-- <?= $form->field($model, 'office')->textInput([]) ?> -->



   <!--  <?= $form->field($model, 'link')->textInput([]) ?> -->

    <?= $form->field($model, 'city_residence')->textInput(['maxlength' => true]) ?>


    <div class="form-group">
    
        
        <?= Html::submitButton($model->isNewRecord ? 'Crear' : 'Actualizar', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
    </div>

    </div>

    <?php ActiveForm::end(); ?>

</div>
<script type="text/javascript">
    
$('#user-identity').keypress(function(e) {
    if(e.which == 13) {
        //console.log('Enter');
      //  consultar_cedula($('#user-identity').val());
    }
});

function consultar_cedula(cedula)
{
    console.log('ajax');
    $.ajax({
       url: '<?php echo Yii::$app->request->baseUrl. 'site/findidentity' ?>',
       type: 'post',
       data: {
                 cedula: cedula
             },
       success: function (data) {
          console.log(data);
          if (data==1)
          {
            $('#formulario').fadeIn();
            //$('.help-block').fadeOut();
            $('#errorMenssage').fadeOut();
            $('#btnconsultar').fadeOut();
            $('#user-names').focus();


          }else{
            //$('#errorMenssage').css("display", "block");
            $('#errorMenssage').fadeIn();
            $('#formulario').fadeOut();
          }
       }
  });
}


</script>

views/user/registro.php
<?php

/* @var $this yii\web\View */
use yii\helpers\Url;
$this->title = 'ASOPREOL | REGÍSTRATE';
use yii\web\View;
use app\models\Slider;
use app\models\Popup;
use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$script=<<< JS
var global_brand='';





$(document).ready(function() {
    $('#user-identity').keypress(function(e) {
    if(e.which == 13) {
        //console.log('Enter');
      //  consultar_cedula($('#user-identity').val());
    }
});


});



JS;
$aux='';
$this->registerJs($script,View::POS_END);
?>
<?php
@$info=$_GET['info'];
if (@$info==1){ $infocontent='Gracias por registrarte en el sistema. Se ha enviado un correo electrónico para que puedas acceder a nuestros servicios. '; }
if (@$info==2){ $infocontent='El usuario ingresado ya se encuentra registrado en el sistema.'; }
if (@$info==3){ $infocontent='La contraseña se ha actualizado con éxito. Ahora puede iniciar sesión y acceder a nuestros servicios.'; }
if (@$info==4){ $infocontent='El token generado es inválido. En caso de tener inconvenientes contáctese con nosotros.'; }
?>


 
        <!-- -->


<section class="container-fluid">
    <div class="servicio" style="padding: 0.5%;">
        <div style="text-align: center;">
            <!--<span style="font-size: 20px;">CESANTÍA</span>
            <div>
                <span class="line-center" style="font-size: 12px">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span>
            </div>-->
        </div>
    </div>
</section>
 
<section class="container-fluid">
    <div class="educacionfinanciera">
        <div class="column1" style="text-align: center;">
            <img style="width: 60%" src="<?= URL::base() ?>/images/site/usericon.fw.png" >
        </div>
        <div class="column2">
            <div style=""><span class="titulo-plan"></span></div>
            <div style="font-family: 'Arial';text-align: justify; font-size: 12px; color: #595959;">
                <br><br>
                <span class="titulo-ef">REGÍSTRATE</span><br>
                <span class="line-center-blue">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span>
                <br>
                
                
                    <?php $form = ActiveForm::begin(); ?>

    <div style="margin-top:10px;margin-bottom:10px;">
        <span>Si eres parte de Asopreol, ingresa tu cédula: </span>
    </div>

    <?= $form->field($model, 'identity')->textInput(['maxlength' => true, 'placeholder'=>'Ej. 1704236757','pattern' => '\d*']) ?>

     <div id="errorMenssage" style="margin-top:10px;margin-bottom:10px;display:none;color:red;">
        <span>Tu cédula no es parte de nuestros registros, por favor comunícate con nosotros para formar parte de Asopreol a los teléfonos: (02) 2222910.</span>
    </div>

    <button id="btnconsultar" type="submit" class="btn btn-success" onclick="javascript:consultar_cedula()">Aceptar</button>

   

    <div id="formulario" style="display:none;">

    <?= $form->field($model, 'names')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'lastnames')->textInput(['maxlength' => true]) ?>

    <!-- <?= $form->field($model, 'type')->textInput(['maxlength' => true]) ?> -->

    <?= $form->field($model, 'address_home')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'phone_home')->textInput(['maxlength' => true, 'placeholder'=>'Ej. 022247845']) ?>

    <?= $form->field($model, 'cellphone')->textInput(['maxlength' => true, 'placeholder'=>'Ej. 0998842367']) ?>

   <!--  <?= $form->field($model, 'cellphone_company')->textInput(['maxlength' => true]) ?> -->

    <?= $form->field($model, 'username')->textInput(['maxlength' => true]) ?>


    <!-- <?= $form->field($model, 'country_origin')->textInput(['maxlength' => true]) ?> -->

    <?= $form->field($model, 'province_residence')->textInput(['maxlength' => true, ]) ?>

    <!-- 'style' => 'text-transform: uppercase' -->

    <?= $form->field($model, 'canton_residence')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'zone_residence')->textInput(['maxlength' => true]) ?>

    <!-- <?= $form->field($model, 'chief_representative')->textInput(['maxlength' => true]) ?> -->

    <!-- <?= $form->field($model, 'secondary_representative')->textInput(['maxlength' => true]) ?> -->


    <!-- <?= $form->field($model, 'office')->textInput([]) ?> -->



   <!--  <?= $form->field($model, 'link')->textInput([]) ?> -->

    <?= $form->field($model, 'city_residence')->textInput(['maxlength' => true]) ?>


    <div class="form-group">
    
        
        <?= Html::submitButton($model->isNewRecord ? 'Crear' : 'Actualizar', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
    </div>

    </div>

    <?php ActiveForm::end(); ?>
                 
            </div>

        </div>
    </div><br>
</section>

<section class="container-fluid">
    <div class="servicio" style="padding: 0.5%;">
        <div style="text-align: center;">
            <!--<span style="font-size: 20px;">CESANTÍA</span>
            <div>
                <span class="line-center" style="font-size: 12px">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span>
            </div>-->
        </div>
    </div>
</section>

<style type="text/css">
.text-content table
{
        width: 100%;
}
.text-content table thead
{
    padding: 2px;
}
.text-content table thead tr th
{
    padding: 2%;
    color: white;
    background-color: #1A185C;
    text-align: center;
    font-size: 14px;
    font-family: 'federo';
    border: 1px solid #1A185C;
    vertical-align: middle;
}
.text-content table tbody tr td
{
    padding: 2%;
    color: black;
    text-align: center;
    font-size: 13px;
    border: 1px solid #1A185C;
    vertical-align: middle;
}
.column1
{
  vertical-align: middle;
  width: 40% !important;
}
.column2
{
  vertical-align: middle !important;
}
.modal {
    display: none; /* Hidden by default */
    position: fixed; /* Stay in place */
    z-index: 1; /* Sit on top */
    left: 0;
    top: 0;
    width: 100%; /* Full width */
    height: 100%; /* Full height */
    overflow: auto; /* Enable scroll if needed */
    background-color: rgb(0,0,0); /* Fallback color */
    background-color: rgba(0,0,0,0.4); /* Black w/ opacity */
}

/* Modal Content/Box */
.modal-content {
    background-color: #fefefe;
    margin: 12% auto; /* 15% from the top and centered */
    padding: 20px;
    border: 1px solid #888;
    width: 26%; /* Could be more or less, depending on screen size */
}

/* The Close Button */
.close {
    color: white;
    float: right;
    font-size: 11px;
    font-weight: bold;
    background: black;
    padding-left: 5px;
    padding-right: 5px;
    opacity: 1;
    height: 15px;
    margin-left: 5px;
}

.close:hover,
.close:focus {
    color: black;
    text-decoration: none;
    cursor: pointer;
}
</style>
<?php 

if (@$info || @$popup)
{
    ?>
    <script>
        var modal = document.getElementById('myModal');
        var btn = document.getElementById("myBtn");

        // Get the <span> element that closes the modal
        var span = document.getElementsByClassName("close")[0];

        var datos= false;
        modal.style.display = "block";

        span.onclick = function() {
        modal.style.display = "none";
    }

    // When the user clicks anywhere outside of the modal, close it
    window.onclick = function(event) {
        if (event.target == modal) {
            modal.style.display = "none";
        }
    }
    </script>
    <?php
}

?>
<script type="text/javascript">
	
function consultar_cedula()
{
	cedula=$('#user-identity').val();
    console.log('ajax');
    $.ajax({
       url: '<?php echo Yii::$app->request->baseUrl. '/site/findidentity' ?>',
       type: 'post',
       data: {
                 cedula: cedula
             },
       success: function (data) {
          console.log(data);
          if (data==1)
          {
            $('#formulario').fadeIn();
            //$('.help-block').fadeOut();
            $('#errorMenssage').fadeOut();
            $('#btnconsultar').fadeOut();
            $('#user-names').focus();


          }else{
            //$('#errorMenssage').css("display", "block");
            $('#errorMenssage').fadeIn();
            $('#formulario').fadeOut();
          }
       }
  });
}
</script>

 